export const LOAD_WEATHER = 'LOAD_WEATHER';
export const LOAD_WEATHER_SUCCESS = 'LOAD_WEATHER_SUCCESS';
export const LOAD_WEATHER_ERROR = 'LOAD_WEATHER_ERROR';

export const CHANGE_SEARCH_INPUT = 'CHANGE_SEARCH_INPUT';
